In [1]:
import numpy as np

from ListArrayConversion import third_array

In [3]:
first_array = np.arange(10)
first_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
updated_first_array = np.insert(first_array,9,10)
updated_first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10,  9])

In [13]:
second_array = np.arange(20)
second_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
updated_second_array = np.append(second_array,100)
updated_second_array


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100])

In [16]:
third_array = np.arange(6)
third_array

array([0, 1, 2, 3, 4, 5])

In [18]:
updated_third_array = np.delete(third_array,3)
updated_third_array

array([0, 1, 2, 4, 5])

In [20]:
integers_array = np.random.randint(0,20,20)
integers_array

array([18, 18, 18, 16,  9, 19,  1,  2, 19, 18,  5,  2, 16, 19, 17, 13, 14,
        5, 15, 10])

In [24]:
print(np.sort(integers_array))

[ 1  2  2  5  5  9 10 13 14 15 16 16 17 18 18 18 18 19 19 19]


In [26]:
integers_two_dim_array = np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_two_dim_array

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [28]:
print(np.sort(integers_two_dim_array))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [30]:
colors = np.array(['red','green','blue','yellow'])
colors

array(['red', 'green', 'blue', 'yellow'], dtype='<U6')

In [31]:
print(np.sort(colors))

['blue' 'green' 'red' 'yellow']
