In [1]:
import numpy as np

In [3]:
first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
second_arr = np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
third_arr = np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [8]:
first_arr.sum()

np.int64(550)

In [9]:
second_arr.sum()

np.int64(450)

In [10]:
third_arr.sum()

np.int64(550)

In [12]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [14]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [15]:
first_arr.prod()

np.int64(36288000000000000)

In [16]:
second_arr.prod()

np.int64(362880000000000)

In [17]:
third_arr.prod()

np.int64(36288000000000000)

In [18]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [20]:
np.average(first_arr)

np.float64(55.0)

In [21]:
np.average(second_arr)

np.float64(50.0)

In [23]:
np.average(third_arr)

np.float64(55.0)

In [25]:
np.min(first_arr)
np.min(second_arr)
np.min(third_arr)

np.int64(10)

In [27]:
np.max(first_arr)
np.max(second_arr)
np.max(third_arr)

np.int64(100)

In [29]:
np.mean(first_arr)
np.mean(second_arr)
np.mean(third_arr)

np.float64(55.0)

In [30]:
np.std(first_arr)
np.std(second_arr)
np.std(third_arr)

np.float64(28.722813232690143)