In [2]:
import numpy as np

In [5]:
a=np.arange(1,11)
b=np.arange(21,31)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[21 22 23 24 25 26 27 28 29 30]


In [6]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [7]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [8]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [9]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [11]:
c=np.arange(2,12)
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a**c

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [14]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [16]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [17]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [18]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [19]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [20]:
np.power(a,c)

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [21]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])