In [1]:
import numpy as np

In [3]:
first_zero_array = np.zeros(5)
first_zero_array

array([0., 0., 0., 0., 0.])

In [5]:
second_zero_array = np.zeros((4,5))
second_zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
first_ones_array = np.ones(5)
first_ones_array

array([1., 1., 1., 1., 1.])

In [10]:
second_ones_array = np.ones((4,5),dtype=int)
second_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
first_fill_array = np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array


array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [13]:
second_full_array = np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])