In [1]:
import numpy as np

In [3]:
first_array = np.arange(1,13)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
second_array = np.reshape(first_array,(3,4))
second_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
third_array = np.reshape(first_array,(6,2))
third_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
fourth_array = np.reshape(first_array,(3,2,2))
fourth_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
fifth_array = np.array([[1,2],[3,4],[5,6]])
fifth_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
sixth_array = np.reshape(fifth_array,-1)
sixth_array

array([1, 2, 3, 4, 5, 6])

In [15]:
seventh_array = fifth_array.flatten()
eighth_array = fifth_array.ravel()
eighth_array[0] = 8
print("Seventh Array: ", seventh_array)
print("Eighth Array: ", eighth_array)
print("Fifth Array: ", fifth_array)

Seventh Array:  [1 2 3 4 5 6]
Eighth Array:  [8 2 3 4 5 6]
Fifth Array:  [[8 2]
 [3 4]
 [5 6]]
