In [1]:
import numpy as np

In [3]:
students_ids_number = np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [5]:
students_ids_number_reg = students_ids_number
print("id of students_ids_number", id(students_ids_number_reg))
print("id of students_ids_number-reg",id(students_ids_number_reg))

id of students_ids_number 4439078928
id of students_ids_number-reg 4439078928


In [7]:
students_ids_number_reg[1]=2222
print(students_ids_number_reg)
print(students_ids_number)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [9]:
students_ids_number_cp = students_ids_number.copy()
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [11]:
print(students_ids_number == students_ids_number_cp)

[ True  True  True  True  True  True  True  True]


In [16]:
print("Id of students_ids_number",id(students_ids_number))
print("Id of students_ids_number_cp",id(students_ids_number_cp))

Id of students_ids_number 4439078928
Id of students_ids_number_cp 4439075568


In [15]:
students_ids_number[0] = 1000
print("Original",students_ids_number)
print("End", students_ids_number_cp)

Original [1000 2222 1313 1414 1515 1616 1717 1818]
End [1111 2222 1313 1414 1515 1616 1717 1818]


In [17]:
students_ids_number_v = students_ids_number.view()

In [19]:
students_ids_number_v[0] = 2000
print("Original",students_ids_number)
print("View", students_ids_number_v)

Original [2000 2222 1313 1414 1515 1616 1717 1818]
View [2000 2222 1313 1414 1515 1616 1717 1818]


In [20]:
print(students_ids_number.base)
print(students_ids_number_reg.base)
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
None
None
[2000 2222 1313 1414 1515 1616 1717 1818]
