In [1]:
import numpy as np

In [3]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
integers_second_array = np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [7]:
integers_third_array = np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [11]:
floating_first_array = np.linspace(10,20)
floating_first_array

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [13]:
floating_second_array = np.linspace(10,20,5)
floating_second_array

array([10. , 12.5, 15. , 17.5, 20. ])

In [15]:
random_first_array = np.random.rand(10)
random_first_array

array([0.79904446, 0.3456101 , 0.51072568, 0.24781979, 0.8961268 ,
       0.11892676, 0.15864734, 0.76753332, 0.19923563, 0.39065718])

In [17]:
random_second_array = np.random.rand(4,4)
random_second_array

array([[0.49310602, 0.67111734, 0.14450773, 0.92151969],
       [0.11836355, 0.58648465, 0.72333411, 0.81021541],
       [0.70940356, 0.86227541, 0.92889327, 0.47331172],
       [0.94019948, 0.18893317, 0.41781153, 0.48881454]])

In [24]:
random_third_arrayy = np.random.randint(0,100,10)
random_third_arrayy

array([86, 51, 78, 61, 61, 63, 72, 46, 88, 50])