In [1]:
import numpy as np

In [3]:
list_obj = [1,2,3,4,5,6]

In [5]:
list_obj

[1, 2, 3, 4, 5, 6]

In [7]:
array_obj = np.array(list_obj)

In [8]:
array_obj

array([1, 2, 3, 4, 5, 6])

In [10]:
second_list = [1,2,3,-1.23,50,128000.56,4.56]

In [12]:
second_list

[1, 2, 3, -1.23, 50, 128000.56, 4.56]

In [14]:
second_array = np.array(second_list)

In [16]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [18]:
third_list = ['Ann',1111,'Peter',22222,44444,55555]
third_list

['Ann', 1111, 'Peter', 22222, 44444, 55555]

In [20]:
third_array = np.array(third_list)
third_array

array(['Ann', '1111', 'Peter', '22222', '44444', '55555'], dtype='<U21')

In [22]:
first_tuple = (1,2,3,4,5,6)
first_tuple

(1, 2, 3, 4, 5, 6)

In [24]:
array_first_tuple = np.array(first_tuple)
array_first_tuple

array([1, 2, 3, 4, 5, 6])

In [25]:
multi_dim_list = [[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]

In [27]:
multi_dim_list

[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]

In [28]:
array_from_multi_dim_list = np.array(multi_dim_list)
array_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])