In [1]:
import numpy as np

In [4]:
first_arr = np.arange(1,13)
first_arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
second_arr = np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
third_arr = np.reshape(first_arr,(3,2,2))
print(third_arr)
print("Dimensions of third_arr is ", third_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of third_arr is  3


In [9]:
fourth_arr = np.reshape([[1,2],[3,4],[5,6]],-1)
fourth_arr

array([1, 2, 3, 4, 5, 6])