In [1]:
import numpy as np

In [3]:
first_arr = np.arange(12).reshape(3,4)
first_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.transpose(first_arr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
second_arr = np.arange(6).reshape(3,2)
second_arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
np.transpose(second_arr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [17]:
third_arr = np.arange(24).reshape(2,3,4)
third_arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
np.moveaxis(third_arr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])