In [2]:
import numpy as np

In [3]:
first_arr = np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [5]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [8]:
second_arr = ([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

[[1, 1, 2, 1], [3, 1, 2, 1], [1, 1, 2, 1], [7, 1, 1, 1]]

In [10]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [12]:
np.unique(second_arr, axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [13]:
np.unique(second_arr, axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [15]:
np.unique(first_arr, return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11]))

In [17]:
np.unique(second_arr, return_index=True)


(array([1, 2, 3, 7]), array([ 0,  2,  4, 12]))

In [18]:
np.unique(second_arr, return_countsz=True)


(array([1, 2, 3, 7]), array([11,  3,  1,  1]))